//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxHunt
{
    public partial class Admin
    {
        protected global::System.Web.UI.WebControls.Repeater rptConfig;
        protected global::System.Web.UI.WebControls.Button btnReseedBands;
        protected global::System.Web.UI.WebControls.Button btnPurgeReports;
        protected global::System.Web.UI.WebControls.Literal litStatus;
    }
}
