//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxHunt
{
    public partial class Bands
    {
        protected global::System.Web.UI.WebControls.Repeater rptBands;
    }
}
