//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxHunt
{
    public partial class Hunt
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlTarget;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl foxBandPill;
    }
}
