//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxHunt
{
    public partial class Sessions
    {
        protected global::System.Web.UI.WebControls.Repeater rptSessions;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl foxSessionsEmpty;
    }
}
