//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxHunt
{
    public partial class Targets
    {
        protected global::System.Web.UI.WebControls.HiddenField hfTargetId;
        protected global::System.Web.UI.WebControls.TextBox txtCallsign;
        protected global::System.Web.UI.WebControls.TextBox txtNickname;
        protected global::System.Web.UI.WebControls.DropDownList ddlBand;
        protected global::System.Web.UI.WebControls.TextBox txtFreqHz;
        protected global::System.Web.UI.WebControls.TextBox txtNotes;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnClear;
        protected global::System.Web.UI.WebControls.Repeater rptTargets;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl foxTargetsEmpty;
    }
}
